### ISSUE TITLE
Slow file-directory write-delete operations And 

### ISSUE THREAD

**Issue by selimozdemir** [linuxdeepin/dde-file-manager#44] opened 2018-09-15 16:31 UTC
Moving a file or folder-copy-delete operations takes a very long time.

Another problem is that sometimes the files do not appear even though they seem to have been completed. (It happens in a device like USB flash disk in a different memory.)

## Enviroments

Distro: Deepin 15.7
Version: 4.15.0-29deepin-generic

**Comment by BLumia** [comment] 2018-09-17 02:55
Did your folder contains a lot of files and/or large files? It's normal if that take longer time than normal folder.

For the second question, if some other program (like vscode) used a lot of inotify "watch handle", the file manager app may run out of inotify watch handle to use and will cause it can't watch the file changes. You can set the inotify value [by modify fs.inotify.max_user_watches](https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit).

So it's probably not a bug, gotta close this issue. Feel free to reopen this issue if you can provide minimum steps to help us reproduce and confirm the bug exist.

**Closed as completed by BLumia** 2018-09-17 02:55 UTC

**Comment by selimozdemir** [comment] 2018-09-17 12:49
It takes a lot longer than it should, for example, I assume I've deleted a single file,
Deletes the file for 5 seconds.

And fs.inotify.max_user_watches = 524288 looks like this. Should I drop?

I changed the file system with nemo because of the slowness in deepin file manager.
Nemo works pretty well now. I'll use it until the bugs are fixed.

**Comment by BLumia** [comment] 2018-09-17 12:54
Which file system did you use? Did nautilus got the same thing happened? It will be much more helpful if you can provide more details so we can reproduce the problem and fix it.

btw, the package version of dde-file-manager is probably wrong. You can use `apt policy dde-file-manager` to get the package version.

**Comment by selimozdemir** [comment] 2018-09-17 13:03
I'm using Nemo file manager. There's no problem right now.

I installed gnome and gdm tools in the system, when I logged in with gdm, I saw that there was no error in nautilus.
So I think the error is related to dde file manager, other file systems are working properly.

And I make a note,
These errors occurred after the last update of the system.

Is there any other information you need to solve the problem?

**Comment by BLumia** [comment] 2018-09-17 15:19
No I means which [file system](https://en.wikipedia.org/wiki/File_system) you are using, not which file manager app you are using.

Since nautilus works well, dde-file-manager should also works without problem when you do local file operations (till the current lastest release, both dde-file-manager and nautilus use gvfs as backend).

You still not provided the correct package version btw... Personally I recommend you perform a `sudo apt update` , `sudo apt install dde` and `sudo apt upgrade` to ensure you are using the lastest version of dde with all componments installed, and check again if the issue still happened,
