### ISSUE TITLE
Can't browse android devices

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#48] opened 2018-09-26 09:20 UTC
Deepin file manager can't browse Android devices. 
It says that an Android device is connected but it doesn't show any files when it is mounted. By the way, Nautilus file manager seems to be able to show files.

## To Reproduce

To reproduce it, just attach an android to the computer via USB. You will see that Deepin file manager doesn't show any files.

## Expected behavior

I am expected to be able to see all the files of my Android device in Deepin file manager.

## Environments *(please complete the following information):*

 - Distro: Archlinux
 - Version: Latest

**Comment by BLumia** [comment] 2018-09-26 13:21
Works on my machine with my oneplus 3T, can't reproduce here :( You've mentioned nautilus **seems** works, double check if it works. 

If nautilus works as expected, close all dde-file-manager instance and open up a terminal simulater application like deepin-terminal, run `QT_LOGGING_RULES="*.debug=true"` from terminal and then run `dde-file-manager` from the same terminal session. Then you'll get dde-file-manager running with debug log enabled. Try click the android device item from the sidebar and paste the related log, thx.

**Comment by SiamSami** [comment] 2018-09-26 13:47
It doesn't work on my Samsung J500H.

**Comment by BLumia** [comment] 2018-09-26 14:10
Probably related: #4 .

Did you check if nautilus works?

**Comment by SiamSami** [comment] 2018-09-26 14:14
If type `QT_LOGGIN_RULES="*.debug=true"` and then run dde-file-manager, then when I try to mount my Android device, it gives me this message,

> [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 99] false "" "lsblk: /dev/bus/usb/002/005: not a block device\n"

**Comment by BLumia** [comment] 2018-09-27 01:15
It'll be very helpful if you can provide the full log of that session, and *did you check again if nautilus works?*

Checkout #4 and see if install `gvfs-mtp` or other method mentioned in that issue can solve the problem, if you are getting the same issue as #4, we'll close this issue as it's duplicate..

**Comment by SiamSami** [comment] 2018-09-27 05:29
`gvfs-mtp` package is already installed. But it still doesn't work.

**Comment by BLumia** [comment] 2018-09-27 14:47
*did you check again if nautilus works?*

**Comment by SiamSami** [comment] 2018-09-28 03:50
Yes, I checked again and nautilus works. And since asked for a log, here it is,

> "dtkwidget2" can not find qm files
> "dde-file-manager" can not find qm files
> 2018-09-28, 09:47:24.426 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           73] "/usr/lib/dde-file-manager/plugins"
> 2018-09-28, 09:47:24.426 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           77] load plugin in:  "/usr/lib/dde-file-manager/plugins/menu"
> 2018-09-28, 09:47:24.426 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           77] load plugin in:  "/usr/lib/dde-file-manager/plugins/view"
> 2018-09-28, 09:47:24.426 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           77] load plugin in:  "/usr/lib/dde-file-manager/plugins/preview"
> 2018-09-28, 09:47:24.426 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           112] menu plugin size: 0
> 2018-09-28, 09:47:24.426 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           113] expand info size: 0
> 2018-09-28, 09:47:24.426 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           114] view size: 0
> 2018-09-28, 09:47:24.427 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           73] "/usr/lib/dde-file-manager/plugins"
> 2018-09-28, 09:47:24.427 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           77] load plugin in:  "/usr/lib/dde-file-manager/plugins/menu"
> 2018-09-28, 09:47:24.427 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           77] load plugin in:  "/usr/lib/dde-file-manager/plugins/view"
> 2018-09-28, 09:47:24.427 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           77] load plugin in:  "/usr/lib/dde-file-manager/plugins/preview"
> 2018-09-28, 09:47:24.427 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           112] menu plugin size: 0
> 2018-09-28, 09:47:24.427 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           113] expand info size: 0
> 2018-09-28, 09:47:24.427 [Debug  ] [pluginmanager.cpp    PluginManager::loadPlugin           114] view size: 0
> 2018-09-28, 09:47:24.465 [Debug  ] [networkmanager.cpp   NetworkManager::NetworkManager      113] Create NetworkManager
> 2018-09-28, 09:47:24.465 [Debug  ] [secretmanager.cpp    SecretManager::SecretManager        41] Create SecretManager
> 2018-09-28, 09:47:24.465 [Debug  ] [fileutils.cpp        FileUtils::migrateConfigFileFromCache 927] Could not read source file  "/home/toor/.cache/dde-file-manager/samba.json" : "No such file or directory"
> 2018-09-28, 09:47:24.465 [Debug  ] [fileutils.cpp        FileUtils::migrateConfigFileFromCache 931] Failed to migrate config file from cache
> 2018-09-28, 09:47:24.465 [Debug  ] [secretmanager.cpp    SecretManager::loadCache            162] Couldn't write samba file!
> DFileSystemWatcherPrivate::addPaths: inotify_add_watch failed: No such file or directory
> 2018-09-28, 09:47:24.465 [Warning] [dfilewatcher.cpp     DFileWatcherPrivate::start          86] virtual bool DFileWatcherPrivate::start() start watch failed, file path = "/var/lib/samba/usershares"
> 2018-09-28, 09:47:24.467 [Debug  ] [appcontroller.cpp    AppController::createDBusInterface::lambda 916] com.deepin.SessionManager : StartManager has LaunchApp interface
> 2018-09-28, 09:47:24.553 [Warning] [dthememanager.cpp    Dtk::Widget::DThemeManagerPrivate::registerWidget 234] can not load qss with out filename dde_file_manager::DFMSideBar(0x7f33952e7ec0)
> 2018-09-28, 09:47:24.554 [Warning] [                                                         0] QLayout: Attempting to add QLayout "" to DFileManagerWindow "", which already has a layout
> 2018-09-28, 09:47:24.589 [Warning] [                                                         0] QObject::connect: Cannot connect Dtk::Widget::DTitlebar::minimumClicked() to (null)::showMinimized()
> 2018-09-28, 09:47:24.589 [Warning] [                                                         0] QObject::connect: Cannot connect Dtk::Widget::DTitlebar::maximumClicked() to (null)::showMaximized()
> 2018-09-28, 09:47:24.589 [Warning] [                                                         0] QObject::connect: Cannot connect Dtk::Widget::DTitlebar::restoreClicked() to (null)::showNormal()
> 2018-09-28, 09:47:24.589 [Warning] [                                                         0] QObject::connect: Cannot connect Dtk::Widget::DTitlebar::closeClicked() to (null)::close()
> 2018-09-28, 09:47:24.589 [Warning] [                                                         0] Could not parse stylesheet of object 0x7f33953c7900
> 2018-09-28, 09:47:24.597 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           837] ===========volumeAdded============= "/" false false
> 2018-09-28, 09:47:24.597 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           838] QDiskInfo(id: "/",name: "System Disk",type: "native",drive_unix_device: "",unix_device: "",uuid: "",activation_root_uri: "",mounted_root_uri: "/",id_filesystem: "",default_location: "",iconName: "",is_removable: false,can_mount: false,can_unmount: false,can_eject: false,used: 50910523392,total: 112894316544,)
> 2018-09-28, 09:47:24.600 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 99] false "" "lsblk: : not a block device\n"
> 2018-09-28, 09:47:24.624 [Warning] [                                                         0] Could not parse stylesheet of object 0x7f33953c7900
> 2018-09-28, 09:47:24.626 [Warning] [                                                         0] Could not parse stylesheet of object 0x7f33953c7900
> 2018-09-28, 09:47:24.641 [Warning] [                                                         0] Could not parse stylesheet of object 0x7f33953c7900
> 2018-09-28, 09:47:24.664 [Debug  ] [windowmanager.cpp    WindowManager::showNewWindow        179] new window 75497482 DUrl("computer:///")
> 2018-09-28, 09:47:24.680 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     466] QDiskInfo(id: "/dev/sda1",name: "New Volume",type: "native",drive_unix_device: "/dev/sda",unix_device: "/dev/sda1",uuid: "1AB6E14FB6E12C47",activation_root_uri: "",mounted_root_uri: "file:///media/New%20Volume2",id_filesystem: "l2049",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: false,can_unmount: true,can_eject: false,used: 73359360,total: 209711104,)
> 2018-09-28, 09:47:24.680 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] true "/dev/sda"
> 2018-09-28, 09:47:24.681 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           837] ===========volumeAdded============= "/dev/sda1" false false
> 2018-09-28, 09:47:24.681 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           838] QDiskInfo(id: "/dev/sda1",name: "New Volume",type: "native",drive_unix_device: "/dev/sda",unix_device: "/dev/sda1",uuid: "1AB6E14FB6E12C47",activation_root_uri: "",mounted_root_uri: "file:///media/New%20Volume2",id_filesystem: "l2049",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: false,can_unmount: true,can_eject: false,used: 73359360,total: 209711104,)
> 2018-09-28, 09:47:24.689 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 91] read usage of "/dev/sda1" false
> 2018-09-28, 09:47:24.692 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] true "/dev/sda"
> 2018-09-28, 09:47:24.692 [Debug  ] [computerview.cpp     ComputerView::mountAdded            908] ===========mountAdded============= "/dev/sda1" true false
> 2018-09-28, 09:47:24.700 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 91] read usage of "/dev/sda1" false
> 2018-09-28, 09:47:24.701 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     484] ()
> 2018-09-28, 09:47:24.702 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     466] QDiskInfo(id: "/dev/sda2",name: "NTFS",type: "native",drive_unix_device: "/dev/sda",unix_device: "/dev/sda2",uuid: "55F75E7D01FBD822",activation_root_uri: "",mounted_root_uri: "file:///media/NTFS1",id_filesystem: "l2050",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: false,can_unmount: true,can_eject: false,used: 86927360000,total: 115240595456,)
> 2018-09-28, 09:47:24.702 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] true "/dev/sda"
> 2018-09-28, 09:47:24.703 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           837] ===========volumeAdded============= "/dev/sda2" false false
> 2018-09-28, 09:47:24.703 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           838] QDiskInfo(id: "/dev/sda2",name: "NTFS",type: "native",drive_unix_device: "/dev/sda",unix_device: "/dev/sda2",uuid: "55F75E7D01FBD822",activation_root_uri: "",mounted_root_uri: "file:///media/NTFS1",id_filesystem: "l2050",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: false,can_unmount: true,can_eject: false,used: 86927360000,total: 115240595456,)
> 2018-09-28, 09:47:24.716 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 91] read usage of "/dev/sda2" false
> 2018-09-28, 09:47:24.719 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] true "/dev/sda"
> 2018-09-28, 09:47:24.719 [Debug  ] [computerview.cpp     ComputerView::mountAdded            908] ===========mountAdded============= "/dev/sda2" true false
> 2018-09-28, 09:47:24.729 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 91] read usage of "/dev/sda2" false
> 2018-09-28, 09:47:24.731 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     484] ()
> 2018-09-28, 09:47:24.731 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     466] QDiskInfo(id: "/dev/sda5",name: "My files",type: "native",drive_unix_device: "/dev/sda",unix_device: "/dev/sda5",uuid: "0F24128063875755",activation_root_uri: "",mounted_root_uri: "file:///media/My%20files2",id_filesystem: "l2053",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: false,can_unmount: true,can_eject: false,used: 86590787584,total: 125544951808,)
> 2018-09-28, 09:47:24.731 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] true "/dev/sda"
> 2018-09-28, 09:47:24.732 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           837] ===========volumeAdded============= "/dev/sda5" false false
> 2018-09-28, 09:47:24.732 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           838] QDiskInfo(id: "/dev/sda5",name: "My files",type: "native",drive_unix_device: "/dev/sda",unix_device: "/dev/sda5",uuid: "0F24128063875755",activation_root_uri: "",mounted_root_uri: "file:///media/My%20files2",id_filesystem: "l2053",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: false,can_unmount: true,can_eject: false,used: 86590787584,total: 125544951808,)
> 2018-09-28, 09:47:24.742 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 91] read usage of "/dev/sda5" false
> 2018-09-28, 09:47:24.746 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] true "/dev/sda"
> 2018-09-28, 09:47:24.746 [Debug  ] [computerview.cpp     ComputerView::mountAdded            908] ===========mountAdded============= "/dev/sda5" true false
> 2018-09-28, 09:47:24.753 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 91] read usage of "/dev/sda5" false
> 2018-09-28, 09:47:24.757 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     484] ()
> 2018-09-28, 09:47:24.757 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     466] QDiskInfo(id: "/dev/sda6",name: "144 GB Volume",type: "native",drive_unix_device: "/dev/sda",unix_device: "/dev/sda6",uuid: "77f55a14-40ea-4c70-b139-ca217639ae99",activation_root_uri: "",mounted_root_uri: "file:///media/77f55a14-40ea-4c70-b139-ca217639ae991",id_filesystem: "l2054",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: false,can_unmount: true,can_eject: false,used: 62951424,total: 140527607808,)
> 2018-09-28, 09:47:24.757 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] true "/dev/sda"
> 2018-09-28, 09:47:24.758 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           837] ===========volumeAdded============= "/dev/sda6" false false
> 2018-09-28, 09:47:24.759 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           838] QDiskInfo(id: "/dev/sda6",name: "144 GB Volume",type: "native",drive_unix_device: "/dev/sda",unix_device: "/dev/sda6",uuid: "77f55a14-40ea-4c70-b139-ca217639ae99",activation_root_uri: "",mounted_root_uri: "file:///media/77f55a14-40ea-4c70-b139-ca217639ae991",id_filesystem: "l2054",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: false,can_unmount: true,can_eject: false,used: 62951424,total: 140527607808,)
> 2018-09-28, 09:47:24.767 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 91] read usage of "/dev/sda6" false
> 2018-09-28, 09:47:24.772 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] true "/dev/sda"
> 2018-09-28, 09:47:24.772 [Debug  ] [computerview.cpp     ComputerView::mountAdded            908] ===========mountAdded============= "/dev/sda6" true false
> 2018-09-28, 09:47:24.779 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 91] read usage of "/dev/sda6" false
> 2018-09-28, 09:47:24.781 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     484] ()
> 2018-09-28, 09:47:24.781 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     466] QDiskInfo(id: "/dev/bus/usb/002/037",name: "SAMSUNG Android",type: "native",drive_unix_device: "",unix_device: "/dev/bus/usb/002/037",uuid: "",activation_root_uri: "mtp://SAMSUNG_SAMSUNG_Android_05e0e0c9/",mounted_root_uri: "",id_filesystem: "",default_location: "",iconName: "multimedia-player",is_removable: false,can_mount: true,can_unmount: false,can_eject: false,used: 0,total: 0,)
> 2018-09-28, 09:47:24.781 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] false ""
> 2018-09-28, 09:47:24.782 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           837] ===========volumeAdded============= "/dev/bus/usb/002/037" false false
> 2018-09-28, 09:47:24.782 [Debug  ] [computerview.cpp     ComputerView::volumeAdded           838] QDiskInfo(id: "/dev/bus/usb/002/037",name: "SAMSUNG Android",type: "native",drive_unix_device: "",unix_device: "/dev/bus/usb/002/037",uuid: "",activation_root_uri: "mtp://SAMSUNG_SAMSUNG_Android_05e0e0c9/",mounted_root_uri: "",id_filesystem: "",default_location: "",iconName: "multimedia-player",is_removable: false,can_mount: true,can_unmount: false,can_eject: false,used: 0,total: 0,)
> 2018-09-28, 09:47:24.786 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 99] false "" "lsblk: /dev/bus/usb/002/037: not a block device\n"
> 2018-09-28, 09:47:24.790 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     484] ()
> 2018-09-28, 09:47:24.810 [Debug  ] [mimesappsmanager.cpp MimesAppsManager::initMimeTypeApps  617] getMimeTypeApps in QThread(0x7f339d6f5870) QThread(0x7f339d6156b0)
> 2018-09-28, 09:47:24.810 [Debug  ] [mimesappsmanager.cpp MimesAppsManager::loadDDEMimeTypes  754] ()
> 2018-09-28, 09:47:24.845 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     466] QDiskInfo(id: "/dev/bus/usb/002/037",name: "SAMSUNG Android",type: "native",drive_unix_device: "",unix_device: "/dev/bus/usb/002/037",uuid: "",activation_root_uri: "mtp://SAMSUNG_SAMSUNG_Android_05e0e0c9/",mounted_root_uri: "mtp://SAMSUNG_SAMSUNG_Android_05e0e0c9/",id_filesystem: "mtp:host=SAMSUNG_SAMSUNG_Android_05e0e0c9",default_location: "",iconName: "multimedia-player",is_removable: false,can_mount: true,can_unmount: true,can_eject: false,used: 9816842240,total: 12410568704,)
> 2018-09-28, 09:47:24.845 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] false ""
> 2018-09-28, 09:47:24.846 [Debug  ] [computerview.cpp     ComputerView::mountAdded            908] ===========mountAdded============= "/dev/bus/usb/002/037" true false
> 2018-09-28, 09:47:24.849 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 99] false "" "lsblk: /dev/bus/usb/002/037: not a block device\n"
> 2018-09-28, 09:47:24.851 [Debug  ] [udisklistener.cpp    UDiskListener::addMountDiskInfo     484] ()
> 2018-09-28, 09:47:25.690 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 99] false "" "lsblk: /dev/bus/usb/002/037: not a block device\n"
> 2018-09-28, 09:47:25.856 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 99] false "" "lsblk: /dev/bus/usb/002/037: not a block device\n"
> 2018-09-28, 09:47:32.342 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::menuActionList     328] DUrl("mtp://samsung_samsung_android_05e0e0c9/")
> 2018-09-28, 09:47:32.343 [Debug  ] [udiskdeviceinfo.cpp  UDiskDeviceInfo::canStop            143] false ""
> 2018-09-28, 09:47:33.461 [Debug  ] [dfilemenumanager.cpp DFileMenuManager::actionTriggered   1017] QAction(0x7f33952b8410 text="Open in new window" toolTip="Open in new window" menuRole=TextHeuristicRole visible=true) true
> 2018-09-28, 09:47:33.461 [Debug  ] [dfilemenumanager.cpp DFileMenuManager::actionTriggered   1042] QAction(0x7f33952b8410 text="Open in new window" toolTip="Open in new window" menuRole=TextHeuristicRole visible=true) QAction(0x7f33952b8410 text="Open in new window" toolTip="Open in new window" menuRole=TextHeuristicRole visible=true)
> 2018-09-28, 09:47:33.461 [Debug  ] [dfilemenumanager.cpp DFileMenuManager::actionTriggered   1044] "Open in new window" "Open in new window"
> 2018-09-28, 09:47:33.461 [Debug  ] [udisklistener.cpp    UDiskListener::mount                591] "/dev/bus/usb/002/037"
> No appenders assotiated with category qt.qpa.xcb
> [Warning] <> QXcbConnection: XCB error: 152 (Unknown), sequence: 2031, resource id: 0, major code: 143 (Unknown), minor code: 2
> 2018-09-28, 09:47:34.418 [Warning] [                                                         0] window == 0 passed.
> No appenders assotiated with category qt.qpa.xcb
> [Warning] <> QXcbConnection: XCB error: 152 (Unknown), sequence: 2484, resource id: 0, major code: 143 (Unknown), minor code: 2
>

**Comment by BLumia** [comment] 2018-09-28 06:30
Thanks, we'll looking into it :)

It's probably the same issue with #4 so just close this one. Further report about this can report to #4 .

**Closed as completed by BLumia** 2018-09-28 06:30 UTC
Labels: bug | functional behavior, duplicate | repeat or similar
